name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        shell: bash
        run: |
            python -m pip install --upgrade pip
            pip install black flake8 invoke
      - name: Lint
        shell: bash
        run: |
            invoke checkformat
            invoke lint

  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Linux py39
            os: ubuntu-latest
            pyversion: '3.9'
          - name: Linux py310
            os: ubuntu-latest
            pyversion: '3.10'
          - name: Windows py39
            os: windows-latest
            pyversion: '3.9'
          - name: MacOS py39
            os: macos-latest
            pyversion: '3.9'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.pyversion }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyversion }}
      - name: Install dependencies
        shell: bash
        run: |
            python -m pip install --upgrade pip
            pip install -U -r requirements.txt
            pip install pytest requests
            python setup.py install
            rm -rf ./timetagger ./build ./egg-info
      - name: Test with pytest
        shell: bash
        run: |
            python -c "import sys; print(sys.version, '\n', sys.prefix)";
            pytest -v .
